version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: urlquery-cli
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: urlquery-cli

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"


release:
  github:
    owner: urlquery
    name: urlquery-cli

checksum:
  name_template: "checksums.txt"